using Argus.Data;
using AutoMapper;
using Argus.Models;
using Argus.Dtos.Auditoriums;
using Argus.Services.Interfaces;
using AutoMapper.QueryableExtensions;
using Microsoft.EntityFrameworkCore;

namespace Argus.Services
{
    public class AuditoriumService(AppDbContext context, IMapper mapper) : IAuditoriumService
    {
        public async Task<List<AuditoriumDto>> GetAllAuditoriumsAsync()
        {
            return await context.Auditoriums
                .AsNoTracking()
                .ProjectTo<AuditoriumDto>(mapper.ConfigurationProvider)
                .ToListAsync();
        }

        public async Task<AuditoriumDto?> GetAuditoriumByIdAsync(Guid id)
        {
            return await context.Auditoriums 
                .AsNoTracking()
                .Where(c => c.Id == id)
                .ProjectTo<AuditoriumDto>( mapper.ConfigurationProvider)
                .FirstOrDefaultAsync();
        }


        public async Task<AuditoriumDto> CreateAuditoriumAsync(CreateAuditoriumDto createAuditoriumDto)
        {
            var newAuditorium = mapper.Map<Auditorium>(createAuditoriumDto);
            
            context.Auditoriums.Add(newAuditorium);
            await context.SaveChangesAsync(); //The Id is generated by the database and linked to the object

            return mapper.Map <AuditoriumDto>(newAuditorium);
        }

        public async Task<bool> DeleteAuditoriumAsync(Guid id)
        {
            var deletedAuditorium = await context.Auditoriums
                .Where(c => c.Id == id)
                .ExecuteDeleteAsync();
            return deletedAuditorium > 0;
        }
    }
}
