// <auto-generated />
using System;
using Argus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Argus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623143409_InitialAuditorium")]
    partial class InitialAuditorium
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Argus.Models.Auditorium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("integer")
                        .HasColumnName("building_number");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_number");

                    b.HasKey("Id")
                        .HasName("pk_auditoriums");

                    b.ToTable("Auditoriums", (string)null);
                });

            modelBuilder.Entity("Argus.Models.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_components");

                    b.ToTable("components", (string)null);
                });

            modelBuilder.Entity("Argus.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inventory_number");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("Argus.Models.PlacementHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uuid")
                        .HasColumnName("auditorium_id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.HasKey("Id")
                        .HasName("pk_placement_histories");

                    b.HasIndex("AuditoriumId")
                        .HasDatabaseName("ix_placement_histories_auditorium_id");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_placement_histories_equipment_id");

                    b.ToTable("placement_histories", (string)null);
                });

            modelBuilder.Entity("Argus.Models.SupportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uuid")
                        .HasColumnName("auditorium_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid?>("ExecutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("executor_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_support_requests");

                    b.HasIndex("AuditoriumId")
                        .HasDatabaseName("ix_support_requests_auditorium_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_support_requests_client_id");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_support_requests_equipment_id");

                    b.HasIndex("ExecutorId")
                        .HasDatabaseName("ix_support_requests_executor_id");

                    b.ToTable("support_requests", (string)null);
                });

            modelBuilder.Entity("Argus.Models.SupportRequestComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("SupportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("support_request_id");

                    b.HasKey("Id")
                        .HasName("pk_support_request_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_support_request_comments_author_id");

                    b.HasIndex("SupportRequestId")
                        .HasDatabaseName("ix_support_request_comments_support_request_id");

                    b.ToTable("support_request_comments", (string)null);
                });

            modelBuilder.Entity("Argus.Models.SupportRequestComponent", b =>
                {
                    b.Property<Guid>("SupportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("support_request_id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("SupportRequestId", "ComponentId")
                        .HasName("pk_support_request_components");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("ix_support_request_components_component_id");

                    b.ToTable("SupportRequestComponents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Quantity_Positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Argus.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Argus.Models.PlacementHistory", b =>
                {
                    b.HasOne("Argus.Models.Auditorium", "Auditorium")
                        .WithMany()
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_placement_histories_auditoriums_auditorium_id");

                    b.HasOne("Argus.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_placement_histories_equipment_equipment_id");

                    b.Navigation("Auditorium");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Argus.Models.SupportRequest", b =>
                {
                    b.HasOne("Argus.Models.Auditorium", "Auditorium")
                        .WithMany()
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_requests_auditoriums_auditorium_id");

                    b.HasOne("Argus.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_requests_users_client_id");

                    b.HasOne("Argus.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_requests_equipment_equipment_id");

                    b.HasOne("Argus.Models.User", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId")
                        .HasConstraintName("fk_support_requests_users_executor_id");

                    b.Navigation("Auditorium");

                    b.Navigation("Client");

                    b.Navigation("Equipment");

                    b.Navigation("Executor");
                });

            modelBuilder.Entity("Argus.Models.SupportRequestComment", b =>
                {
                    b.HasOne("Argus.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_request_comments_users_author_id");

                    b.HasOne("Argus.Models.SupportRequest", "SupportRequest")
                        .WithMany()
                        .HasForeignKey("SupportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_request_comments_support_requests_support_request_id");

                    b.Navigation("Author");

                    b.Navigation("SupportRequest");
                });

            modelBuilder.Entity("Argus.Models.SupportRequestComponent", b =>
                {
                    b.HasOne("Argus.Models.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_support_request_components_components_component_id");

                    b.HasOne("Argus.Models.SupportRequest", "SupportRequest")
                        .WithMany()
                        .HasForeignKey("SupportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_request_components_support_requests_support_request_id");

                    b.Navigation("Component");

                    b.Navigation("SupportRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
